eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/
tagCounter:
  delay:
    initial:
       seconds: 10
    minutes: 1
tagRecommendationCalculation:
  resultCount: 15
keycloak:
  auth-server-url: https://login.archi-lab.io/auth
  bearer-only: true
  cors: false
  principal-attribute: preferred_username
  public-client: false
  realm: archilab
  resource: tag-service
server:
  port: 9003
  use-forward-headers: true
spring:
  application:
    name: tag-service
  datasource:
    password: tag-service
    url: jdbc:postgresql://tag-db:5432/tag-db
    username: tag-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
