eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
keycloak:
  auth-server-url: https://login.archi-lab.io/auth
  bearer-only: true
  cors: false
  principal-attribute: preferred_username
  public-client: false
  realm: archilab
  resource: tag-service
server:
  port: 9003
  use-forward-headers: true
spring:
  application:
    name: tag-service
  datasource:
    password: tag-service
    url: jdbc:h2:mem:testdb
    username: tag-service
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: false


